name: Release

on:
  push:
    tags:        
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x

      - run: deno fmt --check

      - run: deno lint

      - run: deno task test:ci  # TODO(seb): figure out tests that hit prod
      
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}
      
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: npm build
        run: deno task npm ${{steps.get_tag_version.outputs.TAG_VERSION}}
      
      # - name: npm publish
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: cd npm && npm publish
